package com.ui;

import javax.swing.ImageIcon;
import static com.lookandfeel.LookAndFeel.setLookAndFeel;
import com.prototypes.Translator;
import com.window.location.FrameEvents;
import files.FileProcessor;
import java.util.ResourceBundle;

public class LoadMenuFrame extends javax.swing.JFrame implements Translator {
    /**
     * Creates new form LoadMenuFrame
     */
    @SuppressWarnings("LeakingThisInConstructor")
    public LoadMenuFrame()
    {
        initComponents();
        setLanguage();       
        FrameEvents.centerFrame(this);
        progressTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        progressBar.setStringPainted(true);

        imageLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(imageLabel)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progressTask()
    {
        new Thread(() -> 
        {
            for (int index = 1; index <= 100; index++)
            {
                try 
                {
                    progressBar.setValue(index);
                    Thread.sleep(60);
                } 
                catch (InterruptedException ex) {
                    System.err.format("%s%n", ex.getMessage());
                }

                switch (index)
                {
                    case 1:
                        imageLabel.setIcon(new ImageIcon(getClass().getResource(
                                "/com/images/1.png")));
                        break;
                    case 40:
                        imageLabel.setIcon(new ImageIcon(getClass().getResource(
                                "/com/images/2.png")));
                        break;

                    case 60:
                        imageLabel.setIcon(new ImageIcon(getClass().getResource(
                                "/com/images/3.png")));
                        break;

                    case 80:
                        imageLabel.setIcon(new ImageIcon(getClass().getResource(
                                "/com/images/4.png")));
                        break;
                }
                
                if (index == 100)
                {
                    setVisible(false);
                    setLookAndFeel("Windows");
                    new MenuFrame().setVisible(true);
                    break;
                }
            }
        }).start();
    }
    
    private void setLanguage()
    {
        FileProcessor file = FileProcessor.createFile("preference");
        file.loadFile();
        
        String path = file.getProperties().get("file").toString();
        String language = file.getProperties().get("language").toString();
        updateLanguagePreference(path, language);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {    
        setLookAndFeel("Nimbus");   
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoadMenuFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateLanguagePreference(String resource, String locale) {
        ResourceBundle bundle = ResourceBundle.getBundle(resource);
        jLabel1.setText(bundle.getString("menu"));
    }
}
